# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x07predict\"\x8b\x01\n\x0ePredictRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x37\n\x08metadata\x18\x02 \x03(\x0b\x32%.predict.PredictRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"W\n\x0fPredictResponse\x12\x10\n\x08priority\x18\x01 \x01(\x05\x12\x16\n\x0e\x65stimated_time\x18\x02 \x01(\x02\x12\x1a\n\x12recommended_worker\x18\x03 \x01(\t2K\n\x0b\x41IPredictor\x12<\n\x07Predict\x12\x17.predict.PredictRequest\x1a\x18.predict.PredictResponseB:Z8github.com/JamesDante/idtask-scheduler/internal/aiclientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/JamesDante/idtask-scheduler/internal/aiclient'
  _globals['_PREDICTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_PREDICTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=27
  _globals['_PREDICTREQUEST']._serialized_end=166
  _globals['_PREDICTREQUEST_METADATAENTRY']._serialized_start=119
  _globals['_PREDICTREQUEST_METADATAENTRY']._serialized_end=166
  _globals['_PREDICTRESPONSE']._serialized_start=168
  _globals['_PREDICTRESPONSE']._serialized_end=255
  _globals['_AIPREDICTOR']._serialized_start=257
  _globals['_AIPREDICTOR']._serialized_end=332
# @@protoc_insertion_point(module_scope)
