// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: predict.proto

package aiclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_predict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PredictRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PredictResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Priority          int32                  `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	EstimatedTime     float32                `protobuf:"fixed32,2,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
	RecommendedWorker string                 `protobuf:"bytes,3,opt,name=recommended_worker,json=recommendedWorker,proto3" json:"recommended_worker,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_predict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PredictResponse) GetEstimatedTime() float32 {
	if x != nil {
		return x.EstimatedTime
	}
	return 0
}

func (x *PredictResponse) GetRecommendedWorker() string {
	if x != nil {
		return x.RecommendedWorker
	}
	return ""
}

var File_predict_proto protoreflect.FileDescriptor

const file_predict_proto_rawDesc = "" +
	"\n" +
	"\rpredict.proto\x12\apredict\"\xa9\x01\n" +
	"\x0ePredictRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12A\n" +
	"\bmetadata\x18\x02 \x03(\v2%.predict.PredictRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x0fPredictResponse\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\x05R\bpriority\x12%\n" +
	"\x0eestimated_time\x18\x02 \x01(\x02R\restimatedTime\x12-\n" +
	"\x12recommended_worker\x18\x03 \x01(\tR\x11recommendedWorker2K\n" +
	"\vAIPredictor\x12<\n" +
	"\aPredict\x12\x17.predict.PredictRequest\x1a\x18.predict.PredictResponseB:Z8github.com/JamesDante/idtask-scheduler/internal/aiclientb\x06proto3"

var (
	file_predict_proto_rawDescOnce sync.Once
	file_predict_proto_rawDescData []byte
)

func file_predict_proto_rawDescGZIP() []byte {
	file_predict_proto_rawDescOnce.Do(func() {
		file_predict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_predict_proto_rawDesc), len(file_predict_proto_rawDesc)))
	})
	return file_predict_proto_rawDescData
}

var file_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_predict_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: predict.PredictRequest
	(*PredictResponse)(nil), // 1: predict.PredictResponse
	nil,                     // 2: predict.PredictRequest.MetadataEntry
}
var file_predict_proto_depIdxs = []int32{
	2, // 0: predict.PredictRequest.metadata:type_name -> predict.PredictRequest.MetadataEntry
	0, // 1: predict.AIPredictor.Predict:input_type -> predict.PredictRequest
	1, // 2: predict.AIPredictor.Predict:output_type -> predict.PredictResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_predict_proto_init() }
func file_predict_proto_init() {
	if File_predict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_predict_proto_rawDesc), len(file_predict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_predict_proto_goTypes,
		DependencyIndexes: file_predict_proto_depIdxs,
		MessageInfos:      file_predict_proto_msgTypes,
	}.Build()
	File_predict_proto = out.File
	file_predict_proto_goTypes = nil
	file_predict_proto_depIdxs = nil
}
