global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'scheduler'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'worker'
    static_configs:
      - targets: ['host.docker.internal:8083']